### ISSUE TITLE
SEGV in libhfcommon/util.c:171

### ISSUE THREAD

**Issue by project-repo** [google/honggfuzz#188]
Hi, I was trying to get honggfuzz running with instrumentation and as I wasn't quite sure on how to do this I decided to add the -S and -C flags to see what output they produce. I ended up with the following command line:
`~/honggfuzz/honggfuzz -S -C -t 1 -f afl_in/ --covdir_all cov/ --workspace workspace -- ./inst/bin/faac -o /dev/null  ___FILE___ `
When executing this I was surprised to find that honggfuzz threw some errors at me, wrote a file to the workspace directory (which indeed caused a crash in the target) and then segfaulted. To figure out what was going on, I compiled honggfuzz with the address sanitizer. You will find the resulting output below:
```
cmdline: './inst/bin/faac -o /dev/null ___FILE___' pid: 3223, inputDir 'afl_in/', nullifyStdio: true, fuzzStdin: false, saveUnique: true, mutationsPerRun: 6, externalCommand: 'NULL', runEndTime: 0 tmOut: 1, mutationsMax: 0, threads.threadsMax: 8, fileExtn: 'fuzz', ASLimit: 0x0(MiB), RSSLimit: 0x0, DATALimit: 0x0, fuzzExe: './inst/bin/faac', fuzzedPid: 0, monitorSIGABRT: 'true'
[999;1H[2018-02-02T23:04:55+0100][W][3223] files_readFileToBufMax():51 Couldn't open '/sys/bus/event_source/devices/intel_pt/type' for R/O: No such file or directory
[2018-02-02T23:04:55+0100][W][3223] files_readFileToBufMax():51 Couldn't open '/sys/bus/event_source/devices/intel_bts/type' for R/O: No such file or directory
Entering phase 1/2: Dry Run
Launched new fuzzing thread, no. #0
Launched new fuzzing thread, no. #1==3229==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xb03fe340; bottom 0x004ee000; size: 0xaff10340 (-1343159488)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189

Launched new fuzzing thread, no. #2
Launched new fuzzing thread, no. #3
Launched new fuzzing thread, no. #4
Launched new fuzzing thread, no. #5
Launched new fuzzing thread, no. #6
Launched new fuzzing thread, no. #7
Size:44 (i,b,hw,edge,ip,cmp): 0/0/0/0/0/16, Tot:0/0/0/0/0/16
Entering phase 2/2: Dynamic Main
==3238==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xafffe340; bottom 0x004ee000; size: 0xafb10340 (-1347353792)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3239==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xafdfd340; bottom 0x004ee000; size: 0xaf90f340 (-1349455040)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3241==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xafbfc340; bottom 0x004ee000; size: 0xaf70e340 (-1351556288)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3242==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xaf7fa340; bottom 0x004ee000; size: 0xaf30c340 (-1355758784)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3243==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xaf9fb340; bottom 0x004ee000; size: 0xaf50d340 (-1353657536)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3245==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xaf3f8340; bottom 0x004ee000; size: 0xaef0a340 (-1359961280)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3246==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xafdfd340; bottom 0x004ee000; size: 0xaf90f340 (-1349455040)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3247==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xafffe340; bottom 0x004ee000; size: 0xafb10340 (-1347353792)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3248==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xb03fe340; bottom 0x004ee000; size: 0xaff10340 (-1343159488)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3249==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xaf5f9340; bottom 0x004ee000; size: 0xaf10b340 (-1357860032)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3250==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xafbfc340; bottom 0x004ee000; size: 0xaf70e340 (-1351556288)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
[2018-02-02T23:04:55+0100][W][3231] arch_reapChild():368 Un-handled ASan report due to compiler-rt internal error - retry with 'workspace/HF.sanitizer.log.3243'
==3252==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xafffe340; bottom 0x004ee000; size: 0xafb10340 (-1347353792)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
==3253==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xafdfd340; bottom 0x004ee000; size: 0xaf90f340 (-1349455040)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
Ok, that's interesting, saved new crash as 'workspace/SAN.PC.0.STACK.0.CODE.UNKNOWN.ADDR.(nil).INSTR.[UNKNOWN].2018-02-02.23:04:55.fuzz'
ASAN:DEADLYSIGNAL
=================================================================
==3223==ERROR: AddressSanitizer: SEGV on unknown address 0x00000067 (pc 0xb721d216 bp 0xaf9ee6d8 sp 0xaf9ee24c T5)
==3223==The signal is caused by a READ memory access.
==3223==Hint: address points to the zero page.
    #0 0xb721d215  (/usr/lib/i386-linux-gnu/libasan.so.4+0xfe215)
    #1 0xb719423e  (/usr/lib/i386-linux-gnu/libasan.so.4+0x7523e)
==3254==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xaf5f9340; bottom 0x004ee000; size: 0xaf10b340 (-1357860032)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
    #2 0xb71be6ff in vsnprintf (/usr/lib/i386-linux-gnu/libasan.so.4+0x9f6ff)
    #3 0x495302 in util_ssnprintf libhfcommon/util.c:171
    #4 0x48c094 in arch_traceExitSaveData linux/trace.c:1102
    #5 0x48ca65 in arch_traceExitAnalyze linux/trace.c:1153
    #6 0x47e0ea in arch_reapChild linux/arch.c:370
    #7 0x479af5 in subproc_Run /home/jefeus/honggfuzz/subproc.c:343
    #8 0x4609f4 in fuzz_fuzzLoop /home/jefeus/honggfuzz/fuzz.c:438
    #9 0x462527 in fuzz_threadNew /home/jefeus/honggfuzz/fuzz.c:584
    #10 0xb714ded0  (/usr/lib/i386-linux-gnu/libasan.so.4+0x2eed0)
    #11 0xb70ab32c in start_thread (/lib/i386-linux-gnu/libpthread.so.0+0x632c)
    #12 0xb6d49625 in clone (/lib/i386-linux-gnu/libc.so.6+0xec625)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/i386-linux-gnu/libasan.so.4+0xfe215) 
Thread T5 created by T0 here:
    #0 0xb71e6470 in __interceptor_pthread_create (/usr/lib/i386-linux-gnu/libasan.so.4+0xc7470)
    #1 0x462961 in fuzz_runThread /home/jefeus/honggfuzz/fuzz.c:612
    #2 0x462dc9 in fuzz_threadsStart /home/jefeus/honggfuzz/fuzz.c:645
    #3 0x464558 in main /home/jefeus/honggfuzz/honggfuzz.c:219
    #4 0xb6c75455 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18455)

==3223==ABORTING

```
I am unsure what you need in order to track down this bug so just let me know if you need any more information.
cheers
project-repo

**Comment by robertswiecki** [comment]
Hm.. the old implementation of util_vssnprintf looked good, but I simplified it a bit - https://github.com/google/honggfuzz/commit/1d170fb225bbbf753a057060f04b3d3780fff4a1

Also, technically you don't need to run honggfuzz under ASAN for fuzzing.

As for fuzzing commands, I'd suggest using https://github.com/google/honggfuzz/blob/master/hfuzz_cc/hfuzz-cc.c to compile your binary, this way you won't need to specify -C not -S, which are used for SanCov, which is an older coverage mechanism.

For faac it'd be

```shell
$ CC=/home/jagger/src/honggfuzz/hfuzz_cc/hfuzz-clang CFLAGS="-fsanitize=address" ./configure
$ make -j4
$ cd frontend
$ rm faac
$ /bin/bash ../libtool  --tag=CC   --mode=link /home/jagger/src/honggfuzz/hfuzz_cc/hfuzz-clang  -fsanitize=address   -o faac main.o input.o mp4write.o ../libfaac/libfaac.la -lm -static
```
and then fuzz with

```shell
$ ~/src/honggfuzz/honggfuzz -f IN/ -- ~/src/faac-1.29.9.2/frontend/faac ___FILE___
```
Using -static for libtool avoids creation of a dynamically linked faac command using libfaac.so, this way libfaac.a is statically compiled into faac command.

Also, directly using libfaac.so and creating a persistent fuzzing for that will probably result in much faster fuzzing

**Comment by project-repo** [comment]
Thanks, I will try that. But there still seems to be a bug in honggfuzz because the new version continues to segfault when supplied with the input I mention above although the error changed from line 171 to line 153 and the backtrace changed a bit too, probably due to your simplifications. Anyhow, I'll try your method but I still think this should be fixed as fuzzers are supposed to be relatively stable due to the large amount of random data they have to process. There's nothing more anoying then the fuzzer segfaulting after days of fuzzing.

**Comment by project-repo** [comment]
f

**Comment by project-repo** [comment]
Sorry, didn't mean to close the issue. I'm still new to github...

**Comment by robertswiecki** [comment]
Hm.. does it still happen for you? I tested the code (honggfuzz) with asan/msan, and I cannot repeat that. And the point of failure is a bit strange, it's basically snprintf(buf, sizeof(buf), "sth") where seems to be of a fixed size (inside struct) and correctly initialized to [0]='\0' - with  https://github.com/google/honggfuzz/blob/master/linux/trace.c#L569

**Comment by project-repo** [comment]
Yeah, it still occures. It's interesting because it depends on the input file given with the -f option and also on the binary which is being executed which makes it hard to reproduce on other systems. For example I can't reproduce it on a x86_64 bit machine with the same prequisites. I guess it will be hard to debug but if you like I can send you the source directory.

**Comment by robertswiecki** [comment]
Hm.. maybe this? https://github.com/google/honggfuzz/commit/94d314c7a00f0a548fed3526dbcfa523415c88bc

**Comment by project-repo** [comment]
Hmm... No that doesn't seem to be it although the error is now at line 153 and I recieve additional information:
"The address points to the zero page"
Using gdb I figure out that str[len] contains the null address which is leading to this behaviour. It may be interesting to know in addition that len itself is also 0.
If you would like me to run any other tests, don't hesitate to ask.
