### ISSUE TITLE
honggfuzz crashes, sometimes get mangle_getLen error

### ISSUE THREAD

**Issue by taviso** [google/honggfuzz#393]
LTNS Robert!! :smiley: 

I wanted to quickly use honggfuzz to test something, but I couldn't get it working - it crashes (i.e. honggfuzz crashes) after a few seconds. I'm using this commandline:

```
../honggfuzz/honggfuzz -T --timeout 60 -i samples -P -x -- ./rtxharness
```

The crash is not consistent, and doesn't seem to happen with 1 thread, multiple threads seem to be required to trigger it. I often (but not always) see this error in the log before the crash:

```
[2021-04-15T17:27:57-0700][F][507623] mangle_getLen():55 max (1048577) > _HF_INPUT_MAX_SIZE (1048576)
```
I sometimes get an ASAN error like this:

```
==507612==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf5500000 at pc 0xf7a32ea9 bp 0xe99ecae8 sp 0xe99ec6c0
WRITE of size 779427 at 0xf5500000 thread T6
[2021-04-15T17:27:57-0700][F][507623] mangle_getLen():55 max (1048577) > _HF_INPUT_MAX_SIZE (1048576)
    #0 0xf7a32ea8 in __interceptor_memmove ../../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:789
    #1 0x5659ed79 in mangle_Move honggfuzz/mangle.c:101
    #2 0x5659f32b in mangle_Inflate honggfuzz/mangle.c:129
    #3 0x5659f409 in mangle_Insert honggfuzz/mangle.c:139
    #4 0x5659f4c9 in mangle_UseValue honggfuzz/mangle.c:147
    #5 0x565a0aff in mangle_ConstFeedbackDict honggfuzz/mangle.c:519
    #6 0x565a4056 in mangle_mangleContent honggfuzz/mangle.c:902
    #7 0x5659d071 in input_prepareStaticFile honggfuzz/input.c:671
    #8 0x5658d991 in fuzz_fetchInput honggfuzz/fuzz.c:361
    #9 0x5658e41a in fuzz_fuzzLoop honggfuzz/fuzz.c:399
    #10 0x5658fd6c in fuzz_threadNew honggfuzz/fuzz.c:537
    #11 0xf7a533ce in asan_thread_start ../../../../../src/libsanitizer/asan/asan_interceptors.cpp:205
    #12 0xf799b0b3 in start_thread nptl/pthread_create.c:477
    #13 0xf78ae295 in __clone (/lib/i386-linux-gnu/libc.so.6+0x104295)
```

I stopped there, and it does look wrong:

```
#4  0x5659ed7a in mangle_Move (run=0xe9beef60, off_from=99146, off_to=99148, len=949430) at mangle.c:101
101         memmove(&run->dynfile->data[off_to], &run->dynfile->data[off_from], len);
(gdb) p run->dynfile->size
$1 = 1048578
(gdb) p len
$2 = 949430
(gdb) p len + off_to
$3 = 1048578
```

But I don't really understand how that happened?

**Comment by taviso** [comment]
Okay, I can repro on a fresh checkout like this:

I'm at b125038dbcb1a9602be580bfcbbaac8d7180a1bb,

```
$ mkdir samples
$ dd if=/dev/zero bs=1048577 count=1 of=samples/input
1+0 records in
1+0 records out
1048577 bytes (1.0 MB, 1.0 MiB) copied, 0.00091927 s, 1.1 GB/s
$ ./honggfuzz --threads 8 -i samples -x -- /bin/true ___FILE___
```

Note that it doesn't crash *every* time, sometimes you will just get the `mangle_getLen` error or `fuzz_fuzzLoop():404 Cound't prepare input for fuzzing`. If you run it a few times, you will get a segmentation fault (like, 1 in 20 times).

**Comment by taviso** [comment]
Here is valgrind output:

```
$ valgrind --trace-children=no --child-silent-after-fork=yes ./honggfuzz --verbose --threads 8 -i samples -x -- /bin/true ___FILE___
==89246== Memcheck, a memory error detector
==89246== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==89246== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==89246== Command: ./honggfuzz --verbose --threads 8 -i samples -x -- /bin/true ___FILE___
==89246== 
Start time:'2021-04-16.09.34.51' bin:'/bin/true', input:'samples', output:'samples', persistent:false, stdin:false, mutation_rate:5, timeout:1, max_runs:0, threads:8, minimize:false, git_commit:2518baeec5b43e203c77a0c69cbac7ef400a4633
Entering phase: Static
Launched new fuzzing thread, no. #0
Launched new fuzzing thread, no. #1
Launched new fuzzing thread, no. #2
Launched new fuzzing thread, no. #3
Launched new fuzzing thread, no. #4
Launched new fuzzing thread, no. #5
Launched new fuzzing thread, no. #6
Launched new fuzzing thread, no. #7
==89246== Thread 9:
==89246== Invalid write of size 1
==89246==    at 0x48407EE: memmove (vg_replace_strmem.c:1270)
==89246==    by 0x40E51C: mangle_Move (mangle.c:101)
==89246==    by 0x40E6B6: mangle_Inflate (mangle.c:129)
==89246==    by 0x40E721: mangle_Insert (mangle.c:139)
==89246==    by 0x40E7C4: mangle_UseValue (mangle.c:147)
==89246==    by 0x40EB57: mangle_Bytes (mangle.c:211)
==89246==    by 0x40FB5E: mangle_Splice (mangle.c:780)
==89246==    by 0x40FF29: mangle_mangleContent (mangle.c:889)
==89246==    by 0x40DC6B: input_prepareStaticFile (input.c:670)
==89246==    by 0x409679: fuzz_fetchInput (fuzz.c:361)
==89246==    by 0x409898: fuzz_fuzzLoop (fuzz.c:399)
==89246==    by 0x409F7D: fuzz_threadNew (fuzz.c:537)
==89246==  Address 0x1d020000 is in a rwx anonymous segment
==89246== 
[2021-04-16T09:35:02-0700][F][89259] mangle_getLen():55 max (1048577) > _HF_INPUT_MAX_SIZE (1048576)
==89246== 
==89246== HEAP SUMMARY:
==89246==     in use at exit: 69,240 bytes in 19 blocks
==89246==   total heap usage: 157 allocs, 138 frees, 7,929,963 bytes allocated
==89246== 
==89246== LEAK SUMMARY:
==89246==    definitely lost: 0 bytes in 0 blocks
==89246==    indirectly lost: 0 bytes in 0 blocks
==89246==      possibly lost: 2,736 bytes in 9 blocks
==89246==    still reachable: 66,504 bytes in 10 blocks
==89246==         suppressed: 0 bytes in 0 blocks
==89246== Rerun with --leak-check=full to see details of leaked memory
==89246== 
==89246== For lists of detected and suppressed errors, rerun with: -s
==89246== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

```

I think this is a good hint, maybe the splice operation is trying to extend a file mapping and failing somehow? I might not have time to track down the bug until next week, maybe you know what the problem is just from this 😄

**Comment by taviso** [comment]
Funny, I think if the size of the sample input is `1048576` (rather than `1048577`), it no longer reproduces... that can't be a coincidence? (`1048576` is `0x100000`).

**Comment by robertswiecki** [comment]
Hehe :) 

I think you're implying this perfect code is buggy? :)

Lemme take a look

**Comment by robertswiecki** [comment]
I think the bug is here: https://github.com/google/honggfuzz/blob/master/input.c#L147

It should be locked, when called (the whole rewinddir logic).

Try temporarily to change

```
        if (entry == NULL && rewind) {
            if (!input_getDirStatsAndRewind(run->global)) {
                LOG_E("input_getDirStatsAndRewind('%s')", run->global->io.inputDir);
                return false;
            }
```

with simply

```
     rewinddir(run->global->io.inputDirPtr);
```

and I'll work on a proper fix

**Comment by taviso** [comment]
Confirmed, I don't see any crashes with that change after a few minutes!

**Comment by robertswiecki** [comment]
Thanks and happy fuzzing!

**Comment by taviso** [comment]
Thanks! BTW, is it correct that _HF_INPUT_MAX_SIZE is so small by default? The documentation says it should be 128MB, but I don't think that's true...

`        Maximal size of files processed by the fuzzer in bytes (default: 134217728 = 128MB)`

**Comment by robertswiecki** [comment]
The assumption was that fuzzing files >1MB makes little sense with feedback enabled. And the default maximum size (given no bigger files in the input corpus) is anyway 8KiB.

Keeping it at 128MiB made files in the dynamic corpus grow in size randomly to huge values, b/c adding a lot of random bytes at the end didn't typically lower coverage. So, the decision was made by me to limit it to 1MiB as the lesser of the evils.

In order to raise it to something way bigger we'd need like 3 size limits.

1. Maximum size given no bigger files in the corpus exist (8 KiB)
2. Maximum default size limit (1 MiB) given that files >8KiB exist in the input corpus
3. Maximum size limit defined by users' ```-F```

And that's getting too convoluted -  I'll re-think it, but you can safely change _HF_INPUT_MAX_SIZE to sth bigger for now.
