### ISSUE TITLE
issue with building honggfuzz on debian 10.7 -- error related to bfd?

### ISSUE THREAD

**Issue by evanbaer** [google/honggfuzz#472]
Hi, I am seeing the following issue with honggfuzz in rust-bitcoin --

```
jenkins@bitcoin-ci-3:~/workspace/t/rust-bitcoin/fuzz$ bash -x ./travis-fuzz.sh
+ set -e
++ find . -type f -name '*,*' -o -name '*:*' -o -name '*<*' -o -name '*>*' -o -name '*|*' -o -name '*\?*' -o -name '*\**' -o -name '*"*'
++ wc -l
+ incorrectFilenames=0
+ '[' 0 -gt 0 ']'
+ '[' '' == '' ']'
+ TARGETS='fuzz_targets/*'
+ cargo --version
cargo 1.65.0-nightly (4ed54cecc 2022-08-27)
+ rustc --version
rustc 1.65.0-nightly (2e35f954a 2022-09-01)
+ cargo install --force honggfuzz --no-default-features
    Updating crates.io index
  Downloaded honggfuzz v0.5.55
  Downloaded 1 crate (4.3 MB) in 0.97s
  Installing honggfuzz v0.5.55
  Downloaded rustc_version v0.4.0
  Downloaded semver v1.0.13
  Downloaded 2 crates (41.8 KB) in 0.18s
   Compiling semver v1.0.13
   Compiling honggfuzz v0.5.55
   Compiling rustc_version v0.4.0
    Finished release [optimized] target(s) in 7.18s
  Installing /var/lib/jenkins/.cargo/bin/cargo-hfuzz
  Installing /var/lib/jenkins/.cargo/bin/cargo-honggfuzz
   Installed package `honggfuzz v0.5.55` (executables `cargo-hfuzz`, `cargo-honggfuzz`)
+ for TARGET in $TARGETS
+ echo 'Fuzzing target fuzz_targets/deserialize_address.rs'
Fuzzing target fuzz_targets/deserialize_address.rs
++ basename fuzz_targets/deserialize_address.rs
+ FILENAME=deserialize_address.rs
+ FILE=deserialize_address
+ '[' -d hfuzz_input/deserialize_address ']'
+ HFUZZ_INPUT_ARGS='-f hfuzz_input/deserialize_address/input'
+ HFUZZ_BUILD_ARGS='--features honggfuzz_fuzz'
+ HFUZZ_RUN_ARGS='--run_time 30 --exit_upon_crash -v -f hfuzz_input/deserialize_address/input'
+ cargo hfuzz run deserialize_address
/usr/bin/ld.gold
    Updating crates.io index
  Downloaded cc v1.0.73
  Downloaded 1 crate (57.9 KB) in 0.20s
   Compiling cc v1.0.73
   Compiling semver v1.0.13
   Compiling bitcoin_hashes v0.11.0
   Compiling honggfuzz v0.5.55
   Compiling bech32 v0.9.1
   Compiling lazy_static v1.4.0
   Compiling secp256k1-sys v0.6.0
   Compiling rustc_version v0.4.0
error: failed to run custom build command for `honggfuzz v0.5.55`

Caused by:
  process didn't exit successfully: `/var/lib/jenkins/workspace/t/rust-bitcoin/fuzz/hfuzz_target/release/build/honggfuzz-1414aaf622048ad4/build-script-build` (exit status: 101)
  --- stdout
  make: Entering directory '/var/lib/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.55/honggfuzz'
  rm -f -r core Makefile.bak cmdline.o display.o fuzz.o honggfuzz.o input.o mangle.o report.o sanitizers.o socketfuzzer.o subproc.o linux/arch.o linux/bfd.o linux/perf.o linux/pt.o linux/trace.o linux/unwind.o honggfuzz hfuzz_cc/hfuzz-cc libhfuzz/libhfuzz.a libhfuzz/libhfuzz.so libhfuzz/fetch.o libhfuzz/instrument.o libhfuzz/linux.o libhfuzz/memorycmp.o libhfuzz/performance.o libhfuzz/persistent.o libhfcommon/libhfcommon.a libhfcommon/files.o libhfcommon/log.o libhfcommon/ns.o libhfcommon/util.o libhfnetdriver/libhfnetdriver.a libhfnetdriver/netdriver.o  obj libs ./*.o ./*~ ./core ./*.a ./*.dSYM ./*.la ./*.so ./*.dylib linux/*.o linux/*~ linux/core linux/*.a linux/*.dSYM linux/*.la linux/*.so linux/*.dylib mac/*.o mac/*~ mac/core mac/*.a mac/*.dSYM mac/*.la mac/*.so mac/*.dylib netbsd/*.o netbsd/*~ netbsd/core netbsd/*.a netbsd/*.dSYM netbsd/*.la netbsd/*.so netbsd/*.dylib posix/*.o posix/*~ posix/core posix/*.a posix/*.dSYM posix/*.la posix/*.so posix/*.dylib libhfuzz/*.o libhfuzz/*~ libhfuzz/core libhfuzz/*.a libhfuzz/*.dSYM libhfuzz/*.la libhfuzz/*.so libhfuzz/*.dylib libhfcommon/*.o libhfcommon/*~ libhfcommon/core libhfcommon/*.a libhfcommon/*.dSYM libhfcommon/*.la libhfcommon/*.so libhfcommon/*.dylib libhfnetdriver/*.o libhfnetdriver/*~ libhfnetdriver/core libhfnetdriver/*.a libhfnetdriver/*.dSYM libhfnetdriver/*.la libhfnetdriver/*.so libhfnetdriver/*.dylib
  make: Leaving directory '/var/lib/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.55/honggfuzz'
  make: Entering directory '/var/lib/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.55/honggfuzz'
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o cmdline.o cmdline.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o display.o display.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o fuzz.o fuzz.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o honggfuzz.o honggfuzz.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o input.o input.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o mangle.o mangle.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o report.o report.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o sanitizers.o sanitizers.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o socketfuzzer.o socketfuzzer.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o subproc.o subproc.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o linux/arch.o linux/arch.c
  cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -g -ggdb -g3  -o linux/bfd.o linux/bfd.c
  make: Leaving directory '/var/lib/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.55/honggfuzz'

  --- stderr
  linux/bfd.c: In function ‘arch_bfdDisasm’:
  linux/bfd.c:271:5: error: implicit declaration of function ‘disassemble_free_target’; did you mean ‘disassembler_usage’? [-Werror=implicit-function-declaration]
       disassemble_free_target(&info);
       ^~~~~~~~~~~~~~~~~~~~~~~
       disassembler_usage
  cc1: all warnings being treated as errors
  make: *** [Makefile:263: linux/bfd.o] Error 1
  thread 'main' panicked at 'assertion failed: status.success()', /var/lib/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.55/build.rs:49:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2e35f954ada0f0c777844dc4fa66684efe90a035/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/2e35f954ada0f0c777844dc4fa66684efe90a035/library/core/src/panicking.rs:142:14
     2: core::panicking::panic
               at /rustc/2e35f954ada0f0c777844dc4fa66684efe90a035/library/core/src/panicking.rs:48:5
     3: build_script_build::main
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
jenkins@bitcoin-ci-3:~/workspace/t/rust-bitcoin/fuzz$ 
```

It looks like its coming from here:

```
jenkins@bitcoin-ci-3:~/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.55/honggfuzz$ vim Makefile 
jenkins@bitcoin-ci-3:~/.cargo/registry/src/github.com-1ecc6299db9ec823/honggfuzz-0.5.55/honggfuzz$ make
cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX  -o linux/bfd.o linux/bfd.c
linux/bfd.c: In function ‘arch_bfdDisasm’:
linux/bfd.c:271:5: error: implicit declaration of function ‘disassemble_free_target’; did you mean ‘disassembler_usage’? [-Werror=implicit-function-declaration]
     disassemble_free_target(&info);
     ^~~~~~~~~~~~~~~~~~~~~~~
     disassembler_usage
cc1: all warnings being treated as errors
make: *** [Makefile:263: linux/bfd.o] Error 1
```

Thoughts? This is on a VM running Debian 10.7

**Comment by robertswiecki** [comment]
Please try at HEAD or https://github.com/google/honggfuzz/commit/5a504b49fe829a73b6ea88214d8e4bcf3d103d4f

Unfortunately libbfd/dis-asm offers only an unstable API, it's a problem to work around it.
